# Generated by Django 5.0.3 on 2024-03-22 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0007_category_order_product_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_usage', models.IntegerField(default=1)),
                ('current_usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='login_info',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vouchers',
            field=models.ManyToManyField(blank=True, default=[], related_name='applied_orders', to='alpha.voucher'),
        ),
    ]
