# Generated by Django 5.0.3 on 2024-04-01 05:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0008_voucher_login_info_points_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 5, 50, 28, 948199, tzinfo=datetime.timezone.utc)),
        ),
    ]
